
package org.mixim.examples.platoonBikes;

import org.mixim.base.modules.IBaseApplLayer;
import org.mixim.modules.application.platooning.protocols.BaseProtocol;
import org.mixim.modules.application.platooning.apps.BaseApp;
import org.mixim.modules.application.platooning.UnicastProtocol;
import org.mixim.modules.mobility.traci.TraCIMobility;
import org.mixim.modules.nic.Nic80211p;


module Bike extends Vehicle
{
}
